cabal-version: 3.0
name: ml-service-hs
version: 0.1.0.0
author: Real Limoges
license: BSD-3-Clause
license-file: LICENSE
build-type: Simple
extra-source-files:
  README.md

common warnings
  ghc-options: -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wmissing-export-lists -Wmissing-home-modules -Wpartial-fields -Wredundant-constraints

source-repository head
  type: git
  location: https://github.com/real-limoges/ml-service-hs

library
  default-language: GHC2024
  exposed-modules:
    API
    App
    Types
    Core.Pipeline
    Infrastructure.Queue
    Infrastructure.Repository
    Services.ModelA
    Services.ModelB
    Handlers
  hs-source-dirs:
    src
  ghc-options: -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wmissing-export-lists -Wmissing-home-modules -Wpartial-fields -Wredundant-constraints
  build-depends:
    base ^>=4.20.0.0 && <5,
    text,
    bytestring,
    aeson,
    servant-server,
    warp,
    hedis,
    postgresql-simple,
    resource-pool,
    time,
    uuid,
    mtl,
    transformers



executable ml-service-hs-exe
  import: warnings
  main-is: Main.hs
  hs-source-dirs:
    app,
    src
  default-language: GHC2024
  build-depends:
    base ^>=4.20.0.0
    ml-service-hs,

