cabal-version:      3.12
name:               ml-service-hs
version:            0.1.0.0
author:             Real Limoges
license:            BSD-3-Clause
license-file:       LICENSE
build-type:         Simple
extra-source-files:
    README.md

common warnings
  ghc-options: -Wall
               -Wcompat
               -Widentities
               -Wincomplete-record-updates
               -Wincomplete-uni-patterns
               -Wmissing-export-lists
               -Wmissing-home-modules
               -Wpartial-fields
               -Wredundant-constraints

source-repository head
  type: git
  location: https://github.com/real-limoges/ml-service-hs

library
  default-language: GHC2024
  default-extensions:
    NamedFieldPuns
    OverloadedStrings
    RecordWildCards
    OverloadedRecordDot
    DeriveGeneric
    DeriveAnyClass
    DerivingStrategies
    GeneralizedNewtypeDeriving

  exposed-modules:
    API.Api
    API.App
    API.Dtos
    API.Handlers
    Types
    Core.Pipeline
    Database.Queue
    Database.Repository
    Services.ModelA
    Services.ModelB

  hs-source-dirs:
    src
  build-depends:
        base >=4.20.0.0 && <5
      , vector ^>=0.13.2.0
      , text
      , bytestring
      , aeson
      , servant
      , servant-server
      , http-media
      , warp
      , hedis
      , postgresql-simple
      , resource-pool
      , time
      , uuid
      , mtl
      , transformers
      , cassava
      , uuid



executable ml-service-hs-exe
  import: warnings
  main-is: Main.hs
  hs-source-dirs:
        app
  default-language: GHC2024
  build-depends:
        base >=4.20.0.0 && <5
      , ml-service-hs
      , servant-server
      , warp
      , postgresql-simple
      , hedis
      , resource-pool
      , text